# Generated by Django 3.0.4 on 2020-12-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caisse',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('price', models.IntegerField(db_column='price')),
                ('pictureUrl', models.CharField(db_column='pictureUrl', max_length=255)),
                ('quantity', models.IntegerField(db_column='quantity')),
            ],
            options={
                'db_table': 'caisse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='panier',
            fields=[
                ('idp', models.AutoField(db_column='idp', primary_key=True, serialize=False)),
                ('names', models.CharField(db_column='names', max_length=255)),
                ('quantité', models.IntegerField(db_column='quantité')),
                ('total', models.IntegerField(db_column='total')),
            ],
            options={
                'db_table': 'panier',
                'managed': False,
            },
        ),
    ]
