# Generated by Django 3.0.4 on 2020-12-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_caisse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caisse',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='panier',
            options={'managed': True},
        ),
    ]
